---
- name: "Apache | Create VirtualHosts ({{item.name}})"
  template: 
    src: vhost.j2
    dest: "/etc/apache2/sites-available/{{item.vhost}}.conf"
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
    - Restart Apache2

- name: "Apache | Create htdoc ({{item.name}})"
  file:
    path: "/var/www/{{item.vhost}}"
    state: directory
    mode: 0755
    owner: vagrant
    group: vagrant
  become: yes
  notify:
    - Restart Apache2

- name: "Apache | Enable VirtualHost ({{item.name}})"
  apache2_site: 
    name: "{{item.vhost}}"
    state: present
  become: yes
  notify:
    - Restart Apache2