---
- name: MySQL | Set root password
  debconf:
    name: mysql-server
    question: mysql-server/root_password
    value: root
    vtype: password
  become: yes

- name: MySQL | Set root repassword
  debconf:
    name: mysql-server
    question: mysql-server/root_password_again
    value: root
    vtype: password
  become: yes

- name: MySQL | install
  apt:
    name: mysql-server-5.6
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: MySQL | install python mysql module
  apt:
    name: python-mysqldb
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- include: database.yml
  with_items:
    - "{{vars.vhosts}}"